// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/message.proto

package project2.protos;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PublishRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PublishRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();
  }
  /**
   * Protobuf type {@code PublishRequest}
   */
  public static final class PublishRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PublishRequest)
      PublishRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PublishRequest.newBuilder() to construct.
    private PublishRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PublishRequest() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      topic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PublishRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PublishRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              data_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project2.protos.Message.internal_static_PublishRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project2.protos.Message.internal_static_PublishRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project2.protos.Message.PublishRequest.class, project2.protos.Message.PublishRequest.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int TOPIC_FIELD_NUMBER = 2;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project2.protos.Message.PublishRequest)) {
        return super.equals(obj);
      }
      project2.protos.Message.PublishRequest other = (project2.protos.Message.PublishRequest) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project2.protos.Message.PublishRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.PublishRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.PublishRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.protos.Message.PublishRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static project2.protos.Message.PublishRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.protos.Message.PublishRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project2.protos.Message.PublishRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PublishRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PublishRequest)
        project2.protos.Message.PublishRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project2.protos.Message.internal_static_PublishRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project2.protos.Message.internal_static_PublishRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project2.protos.Message.PublishRequest.class, project2.protos.Message.PublishRequest.Builder.class);
      }

      // Construct using project2.protos.Message.PublishRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        topic_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project2.protos.Message.internal_static_PublishRequest_descriptor;
      }

      @java.lang.Override
      public project2.protos.Message.PublishRequest getDefaultInstanceForType() {
        return project2.protos.Message.PublishRequest.getDefaultInstance();
      }

      @java.lang.Override
      public project2.protos.Message.PublishRequest build() {
        project2.protos.Message.PublishRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project2.protos.Message.PublishRequest buildPartial() {
        project2.protos.Message.PublishRequest result = new project2.protos.Message.PublishRequest(this);
        result.data_ = data_;
        result.topic_ = topic_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project2.protos.Message.PublishRequest) {
          return mergeFrom((project2.protos.Message.PublishRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project2.protos.Message.PublishRequest other) {
        if (other == project2.protos.Message.PublishRequest.getDefaultInstance()) return this;
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project2.protos.Message.PublishRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project2.protos.Message.PublishRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 2;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 2;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PublishRequest)
    }

    // @@protoc_insertion_point(class_scope:PublishRequest)
    private static final project2.protos.Message.PublishRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project2.protos.Message.PublishRequest();
    }

    public static project2.protos.Message.PublishRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PublishRequest>
        PARSER = new com.google.protobuf.AbstractParser<PublishRequest>() {
      @java.lang.Override
      public PublishRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PublishRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PublishRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PublishRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project2.protos.Message.PublishRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PullRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PullRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>int64 startingPosition = 2;</code>
     * @return The startingPosition.
     */
    long getStartingPosition();
  }
  /**
   * Protobuf type {@code PullRequest}
   */
  public static final class PullRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PullRequest)
      PullRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PullRequest.newBuilder() to construct.
    private PullRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullRequest() {
      topic_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PullRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PullRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              topic_ = s;
              break;
            }
            case 16: {

              startingPosition_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project2.protos.Message.internal_static_PullRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project2.protos.Message.internal_static_PullRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project2.protos.Message.PullRequest.class, project2.protos.Message.PullRequest.Builder.class);
    }

    public static final int TOPIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object topic_;
    /**
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTINGPOSITION_FIELD_NUMBER = 2;
    private long startingPosition_;
    /**
     * <code>int64 startingPosition = 2;</code>
     * @return The startingPosition.
     */
    @java.lang.Override
    public long getStartingPosition() {
      return startingPosition_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
      }
      if (startingPosition_ != 0L) {
        output.writeInt64(2, startingPosition_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
      }
      if (startingPosition_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startingPosition_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project2.protos.Message.PullRequest)) {
        return super.equals(obj);
      }
      project2.protos.Message.PullRequest other = (project2.protos.Message.PullRequest) obj;

      if (!getTopic()
          .equals(other.getTopic())) return false;
      if (getStartingPosition()
          != other.getStartingPosition()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPIC_FIELD_NUMBER;
      hash = (53 * hash) + getTopic().hashCode();
      hash = (37 * hash) + STARTINGPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartingPosition());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project2.protos.Message.PullRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.PullRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.PullRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.protos.Message.PullRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static project2.protos.Message.PullRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.protos.Message.PullRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project2.protos.Message.PullRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PullRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PullRequest)
        project2.protos.Message.PullRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project2.protos.Message.internal_static_PullRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project2.protos.Message.internal_static_PullRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project2.protos.Message.PullRequest.class, project2.protos.Message.PullRequest.Builder.class);
      }

      // Construct using project2.protos.Message.PullRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        topic_ = "";

        startingPosition_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project2.protos.Message.internal_static_PullRequest_descriptor;
      }

      @java.lang.Override
      public project2.protos.Message.PullRequest getDefaultInstanceForType() {
        return project2.protos.Message.PullRequest.getDefaultInstance();
      }

      @java.lang.Override
      public project2.protos.Message.PullRequest build() {
        project2.protos.Message.PullRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project2.protos.Message.PullRequest buildPartial() {
        project2.protos.Message.PullRequest result = new project2.protos.Message.PullRequest(this);
        result.topic_ = topic_;
        result.startingPosition_ = startingPosition_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project2.protos.Message.PullRequest) {
          return mergeFrom((project2.protos.Message.PullRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project2.protos.Message.PullRequest other) {
        if (other == project2.protos.Message.PullRequest.getDefaultInstance()) return this;
        if (!other.getTopic().isEmpty()) {
          topic_ = other.topic_;
          onChanged();
        }
        if (other.getStartingPosition() != 0L) {
          setStartingPosition(other.getStartingPosition());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project2.protos.Message.PullRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project2.protos.Message.PullRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object topic_ = "";
      /**
       * <code>string topic = 1;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          topic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string topic = 1;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string topic = 1;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        topic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        
        topic_ = getDefaultInstance().getTopic();
        onChanged();
        return this;
      }
      /**
       * <code>string topic = 1;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        topic_ = value;
        onChanged();
        return this;
      }

      private long startingPosition_ ;
      /**
       * <code>int64 startingPosition = 2;</code>
       * @return The startingPosition.
       */
      @java.lang.Override
      public long getStartingPosition() {
        return startingPosition_;
      }
      /**
       * <code>int64 startingPosition = 2;</code>
       * @param value The startingPosition to set.
       * @return This builder for chaining.
       */
      public Builder setStartingPosition(long value) {
        
        startingPosition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startingPosition = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartingPosition() {
        
        startingPosition_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PullRequest)
    }

    // @@protoc_insertion_point(class_scope:PullRequest)
    private static final project2.protos.Message.PullRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project2.protos.Message.PullRequest();
    }

    public static project2.protos.Message.PullRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullRequest>
        PARSER = new com.google.protobuf.AbstractParser<PullRequest>() {
      @java.lang.Override
      public PullRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project2.protos.Message.PullRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Wrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.PublishRequest pubReq = 1;</code>
     * @return Whether the pubReq field is set.
     */
    boolean hasPubReq();
    /**
     * <code>.PublishRequest pubReq = 1;</code>
     * @return The pubReq.
     */
    project2.protos.Message.PublishRequest getPubReq();
    /**
     * <code>.PublishRequest pubReq = 1;</code>
     */
    project2.protos.Message.PublishRequestOrBuilder getPubReqOrBuilder();

    /**
     * <code>.PullRequest pullReq = 2;</code>
     * @return Whether the pullReq field is set.
     */
    boolean hasPullReq();
    /**
     * <code>.PullRequest pullReq = 2;</code>
     * @return The pullReq.
     */
    project2.protos.Message.PullRequest getPullReq();
    /**
     * <code>.PullRequest pullReq = 2;</code>
     */
    project2.protos.Message.PullRequestOrBuilder getPullReqOrBuilder();

    public project2.protos.Message.Wrapper.MsgCase getMsgCase();
  }
  /**
   * Protobuf type {@code Wrapper}
   */
  public static final class Wrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Wrapper)
      WrapperOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Wrapper.newBuilder() to construct.
    private Wrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wrapper() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Wrapper();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Wrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              project2.protos.Message.PublishRequest.Builder subBuilder = null;
              if (msgCase_ == 1) {
                subBuilder = ((project2.protos.Message.PublishRequest) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(project2.protos.Message.PublishRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((project2.protos.Message.PublishRequest) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 1;
              break;
            }
            case 18: {
              project2.protos.Message.PullRequest.Builder subBuilder = null;
              if (msgCase_ == 2) {
                subBuilder = ((project2.protos.Message.PullRequest) msg_).toBuilder();
              }
              msg_ =
                  input.readMessage(project2.protos.Message.PullRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((project2.protos.Message.PullRequest) msg_);
                msg_ = subBuilder.buildPartial();
              }
              msgCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project2.protos.Message.internal_static_Wrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project2.protos.Message.internal_static_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project2.protos.Message.Wrapper.class, project2.protos.Message.Wrapper.Builder.class);
    }

    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public enum MsgCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PUBREQ(1),
      PULLREQ(2),
      MSG_NOT_SET(0);
      private final int value;
      private MsgCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgCase forNumber(int value) {
        switch (value) {
          case 1: return PUBREQ;
          case 2: return PULLREQ;
          case 0: return MSG_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgCase
    getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public static final int PUBREQ_FIELD_NUMBER = 1;
    /**
     * <code>.PublishRequest pubReq = 1;</code>
     * @return Whether the pubReq field is set.
     */
    @java.lang.Override
    public boolean hasPubReq() {
      return msgCase_ == 1;
    }
    /**
     * <code>.PublishRequest pubReq = 1;</code>
     * @return The pubReq.
     */
    @java.lang.Override
    public project2.protos.Message.PublishRequest getPubReq() {
      if (msgCase_ == 1) {
         return (project2.protos.Message.PublishRequest) msg_;
      }
      return project2.protos.Message.PublishRequest.getDefaultInstance();
    }
    /**
     * <code>.PublishRequest pubReq = 1;</code>
     */
    @java.lang.Override
    public project2.protos.Message.PublishRequestOrBuilder getPubReqOrBuilder() {
      if (msgCase_ == 1) {
         return (project2.protos.Message.PublishRequest) msg_;
      }
      return project2.protos.Message.PublishRequest.getDefaultInstance();
    }

    public static final int PULLREQ_FIELD_NUMBER = 2;
    /**
     * <code>.PullRequest pullReq = 2;</code>
     * @return Whether the pullReq field is set.
     */
    @java.lang.Override
    public boolean hasPullReq() {
      return msgCase_ == 2;
    }
    /**
     * <code>.PullRequest pullReq = 2;</code>
     * @return The pullReq.
     */
    @java.lang.Override
    public project2.protos.Message.PullRequest getPullReq() {
      if (msgCase_ == 2) {
         return (project2.protos.Message.PullRequest) msg_;
      }
      return project2.protos.Message.PullRequest.getDefaultInstance();
    }
    /**
     * <code>.PullRequest pullReq = 2;</code>
     */
    @java.lang.Override
    public project2.protos.Message.PullRequestOrBuilder getPullReqOrBuilder() {
      if (msgCase_ == 2) {
         return (project2.protos.Message.PullRequest) msg_;
      }
      return project2.protos.Message.PullRequest.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgCase_ == 1) {
        output.writeMessage(1, (project2.protos.Message.PublishRequest) msg_);
      }
      if (msgCase_ == 2) {
        output.writeMessage(2, (project2.protos.Message.PullRequest) msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (project2.protos.Message.PublishRequest) msg_);
      }
      if (msgCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (project2.protos.Message.PullRequest) msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project2.protos.Message.Wrapper)) {
        return super.equals(obj);
      }
      project2.protos.Message.Wrapper other = (project2.protos.Message.Wrapper) obj;

      if (!getMsgCase().equals(other.getMsgCase())) return false;
      switch (msgCase_) {
        case 1:
          if (!getPubReq()
              .equals(other.getPubReq())) return false;
          break;
        case 2:
          if (!getPullReq()
              .equals(other.getPullReq())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (msgCase_) {
        case 1:
          hash = (37 * hash) + PUBREQ_FIELD_NUMBER;
          hash = (53 * hash) + getPubReq().hashCode();
          break;
        case 2:
          hash = (37 * hash) + PULLREQ_FIELD_NUMBER;
          hash = (53 * hash) + getPullReq().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project2.protos.Message.Wrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.protos.Message.Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.protos.Message.Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static project2.protos.Message.Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.protos.Message.Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project2.protos.Message.Wrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Wrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Wrapper)
        project2.protos.Message.WrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project2.protos.Message.internal_static_Wrapper_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project2.protos.Message.internal_static_Wrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project2.protos.Message.Wrapper.class, project2.protos.Message.Wrapper.Builder.class);
      }

      // Construct using project2.protos.Message.Wrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgCase_ = 0;
        msg_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project2.protos.Message.internal_static_Wrapper_descriptor;
      }

      @java.lang.Override
      public project2.protos.Message.Wrapper getDefaultInstanceForType() {
        return project2.protos.Message.Wrapper.getDefaultInstance();
      }

      @java.lang.Override
      public project2.protos.Message.Wrapper build() {
        project2.protos.Message.Wrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project2.protos.Message.Wrapper buildPartial() {
        project2.protos.Message.Wrapper result = new project2.protos.Message.Wrapper(this);
        if (msgCase_ == 1) {
          if (pubReqBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = pubReqBuilder_.build();
          }
        }
        if (msgCase_ == 2) {
          if (pullReqBuilder_ == null) {
            result.msg_ = msg_;
          } else {
            result.msg_ = pullReqBuilder_.build();
          }
        }
        result.msgCase_ = msgCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project2.protos.Message.Wrapper) {
          return mergeFrom((project2.protos.Message.Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project2.protos.Message.Wrapper other) {
        if (other == project2.protos.Message.Wrapper.getDefaultInstance()) return this;
        switch (other.getMsgCase()) {
          case PUBREQ: {
            mergePubReq(other.getPubReq());
            break;
          }
          case PULLREQ: {
            mergePullReq(other.getPullReq());
            break;
          }
          case MSG_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project2.protos.Message.Wrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project2.protos.Message.Wrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgCase_ = 0;
      private java.lang.Object msg_;
      public MsgCase
          getMsgCase() {
        return MsgCase.forNumber(
            msgCase_);
      }

      public Builder clearMsg() {
        msgCase_ = 0;
        msg_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          project2.protos.Message.PublishRequest, project2.protos.Message.PublishRequest.Builder, project2.protos.Message.PublishRequestOrBuilder> pubReqBuilder_;
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       * @return Whether the pubReq field is set.
       */
      @java.lang.Override
      public boolean hasPubReq() {
        return msgCase_ == 1;
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       * @return The pubReq.
       */
      @java.lang.Override
      public project2.protos.Message.PublishRequest getPubReq() {
        if (pubReqBuilder_ == null) {
          if (msgCase_ == 1) {
            return (project2.protos.Message.PublishRequest) msg_;
          }
          return project2.protos.Message.PublishRequest.getDefaultInstance();
        } else {
          if (msgCase_ == 1) {
            return pubReqBuilder_.getMessage();
          }
          return project2.protos.Message.PublishRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      public Builder setPubReq(project2.protos.Message.PublishRequest value) {
        if (pubReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          pubReqBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      public Builder setPubReq(
          project2.protos.Message.PublishRequest.Builder builderForValue) {
        if (pubReqBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          pubReqBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      public Builder mergePubReq(project2.protos.Message.PublishRequest value) {
        if (pubReqBuilder_ == null) {
          if (msgCase_ == 1 &&
              msg_ != project2.protos.Message.PublishRequest.getDefaultInstance()) {
            msg_ = project2.protos.Message.PublishRequest.newBuilder((project2.protos.Message.PublishRequest) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 1) {
            pubReqBuilder_.mergeFrom(value);
          }
          pubReqBuilder_.setMessage(value);
        }
        msgCase_ = 1;
        return this;
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      public Builder clearPubReq() {
        if (pubReqBuilder_ == null) {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 1) {
            msgCase_ = 0;
            msg_ = null;
          }
          pubReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      public project2.protos.Message.PublishRequest.Builder getPubReqBuilder() {
        return getPubReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      @java.lang.Override
      public project2.protos.Message.PublishRequestOrBuilder getPubReqOrBuilder() {
        if ((msgCase_ == 1) && (pubReqBuilder_ != null)) {
          return pubReqBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 1) {
            return (project2.protos.Message.PublishRequest) msg_;
          }
          return project2.protos.Message.PublishRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.PublishRequest pubReq = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          project2.protos.Message.PublishRequest, project2.protos.Message.PublishRequest.Builder, project2.protos.Message.PublishRequestOrBuilder> 
          getPubReqFieldBuilder() {
        if (pubReqBuilder_ == null) {
          if (!(msgCase_ == 1)) {
            msg_ = project2.protos.Message.PublishRequest.getDefaultInstance();
          }
          pubReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              project2.protos.Message.PublishRequest, project2.protos.Message.PublishRequest.Builder, project2.protos.Message.PublishRequestOrBuilder>(
                  (project2.protos.Message.PublishRequest) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 1;
        onChanged();;
        return pubReqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          project2.protos.Message.PullRequest, project2.protos.Message.PullRequest.Builder, project2.protos.Message.PullRequestOrBuilder> pullReqBuilder_;
      /**
       * <code>.PullRequest pullReq = 2;</code>
       * @return Whether the pullReq field is set.
       */
      @java.lang.Override
      public boolean hasPullReq() {
        return msgCase_ == 2;
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       * @return The pullReq.
       */
      @java.lang.Override
      public project2.protos.Message.PullRequest getPullReq() {
        if (pullReqBuilder_ == null) {
          if (msgCase_ == 2) {
            return (project2.protos.Message.PullRequest) msg_;
          }
          return project2.protos.Message.PullRequest.getDefaultInstance();
        } else {
          if (msgCase_ == 2) {
            return pullReqBuilder_.getMessage();
          }
          return project2.protos.Message.PullRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      public Builder setPullReq(project2.protos.Message.PullRequest value) {
        if (pullReqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          pullReqBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      public Builder setPullReq(
          project2.protos.Message.PullRequest.Builder builderForValue) {
        if (pullReqBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          pullReqBuilder_.setMessage(builderForValue.build());
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      public Builder mergePullReq(project2.protos.Message.PullRequest value) {
        if (pullReqBuilder_ == null) {
          if (msgCase_ == 2 &&
              msg_ != project2.protos.Message.PullRequest.getDefaultInstance()) {
            msg_ = project2.protos.Message.PullRequest.newBuilder((project2.protos.Message.PullRequest) msg_)
                .mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          if (msgCase_ == 2) {
            pullReqBuilder_.mergeFrom(value);
          }
          pullReqBuilder_.setMessage(value);
        }
        msgCase_ = 2;
        return this;
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      public Builder clearPullReq() {
        if (pullReqBuilder_ == null) {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
            onChanged();
          }
        } else {
          if (msgCase_ == 2) {
            msgCase_ = 0;
            msg_ = null;
          }
          pullReqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      public project2.protos.Message.PullRequest.Builder getPullReqBuilder() {
        return getPullReqFieldBuilder().getBuilder();
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      @java.lang.Override
      public project2.protos.Message.PullRequestOrBuilder getPullReqOrBuilder() {
        if ((msgCase_ == 2) && (pullReqBuilder_ != null)) {
          return pullReqBuilder_.getMessageOrBuilder();
        } else {
          if (msgCase_ == 2) {
            return (project2.protos.Message.PullRequest) msg_;
          }
          return project2.protos.Message.PullRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.PullRequest pullReq = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          project2.protos.Message.PullRequest, project2.protos.Message.PullRequest.Builder, project2.protos.Message.PullRequestOrBuilder> 
          getPullReqFieldBuilder() {
        if (pullReqBuilder_ == null) {
          if (!(msgCase_ == 2)) {
            msg_ = project2.protos.Message.PullRequest.getDefaultInstance();
          }
          pullReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              project2.protos.Message.PullRequest, project2.protos.Message.PullRequest.Builder, project2.protos.Message.PullRequestOrBuilder>(
                  (project2.protos.Message.PullRequest) msg_,
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        msgCase_ = 2;
        onChanged();;
        return pullReqBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Wrapper)
    }

    // @@protoc_insertion_point(class_scope:Wrapper)
    private static final project2.protos.Message.Wrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project2.protos.Message.Wrapper();
    }

    public static project2.protos.Message.Wrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wrapper>
        PARSER = new com.google.protobuf.AbstractParser<Wrapper>() {
      @java.lang.Override
      public Wrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wrapper> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Wrapper> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project2.protos.Message.Wrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublishRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublishRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PullRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Wrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Wrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protos/message.proto\"-\n\016PublishRequest" +
      "\022\014\n\004data\030\001 \001(\014\022\r\n\005topic\030\002 \001(\t\"6\n\013PullReq" +
      "uest\022\r\n\005topic\030\001 \001(\t\022\030\n\020startingPosition\030" +
      "\002 \001(\003\"T\n\007Wrapper\022!\n\006pubReq\030\001 \001(\0132\017.Publi" +
      "shRequestH\000\022\037\n\007pullReq\030\002 \001(\0132\014.PullReque" +
      "stH\000B\005\n\003msgB\032\n\017project2.protosB\007Messageb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PublishRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublishRequest_descriptor,
        new java.lang.String[] { "Data", "Topic", });
    internal_static_PullRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PullRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PullRequest_descriptor,
        new java.lang.String[] { "Topic", "StartingPosition", });
    internal_static_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Wrapper_descriptor,
        new java.lang.String[] { "PubReq", "PullReq", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
