// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/memberShip.proto

package project2.broker.protos;

public final class Membership {
  private Membership() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BrokerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Broker)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>int32 partition = 3;</code>
     * @return The partition.
     */
    int getPartition();

    /**
     * <code>int32 id = 4;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>bool isAsync = 5;</code>
     * @return The isAsync.
     */
    boolean getIsAsync();
  }
  /**
   * Protobuf type {@code Broker}
   */
  public static final class Broker extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Broker)
      BrokerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Broker.newBuilder() to construct.
    private Broker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Broker() {
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Broker();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Broker(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {

              partition_ = input.readInt32();
              break;
            }
            case 32: {

              id_ = input.readInt32();
              break;
            }
            case 40: {

              isAsync_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project2.broker.protos.Membership.internal_static_Broker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project2.broker.protos.Membership.internal_static_Broker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project2.broker.protos.Membership.Broker.class, project2.broker.protos.Membership.Broker.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int PARTITION_FIELD_NUMBER = 3;
    private int partition_;
    /**
     * <code>int32 partition = 3;</code>
     * @return The partition.
     */
    @java.lang.Override
    public int getPartition() {
      return partition_;
    }

    public static final int ID_FIELD_NUMBER = 4;
    private int id_;
    /**
     * <code>int32 id = 4;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ISASYNC_FIELD_NUMBER = 5;
    private boolean isAsync_;
    /**
     * <code>bool isAsync = 5;</code>
     * @return The isAsync.
     */
    @java.lang.Override
    public boolean getIsAsync() {
      return isAsync_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (partition_ != 0) {
        output.writeInt32(3, partition_);
      }
      if (id_ != 0) {
        output.writeInt32(4, id_);
      }
      if (isAsync_ != false) {
        output.writeBool(5, isAsync_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (partition_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, partition_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, id_);
      }
      if (isAsync_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isAsync_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project2.broker.protos.Membership.Broker)) {
        return super.equals(obj);
      }
      project2.broker.protos.Membership.Broker other = (project2.broker.protos.Membership.Broker) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (getPartition()
          != other.getPartition()) return false;
      if (getId()
          != other.getId()) return false;
      if (getIsAsync()
          != other.getIsAsync()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + PARTITION_FIELD_NUMBER;
      hash = (53 * hash) + getPartition();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ISASYNC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsAsync());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project2.broker.protos.Membership.Broker parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Broker parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.Broker parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.Broker parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project2.broker.protos.Membership.Broker prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Broker}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Broker)
        project2.broker.protos.Membership.BrokerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project2.broker.protos.Membership.internal_static_Broker_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project2.broker.protos.Membership.internal_static_Broker_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project2.broker.protos.Membership.Broker.class, project2.broker.protos.Membership.Broker.Builder.class);
      }

      // Construct using project2.broker.protos.Membership.Broker.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        address_ = "";

        port_ = 0;

        partition_ = 0;

        id_ = 0;

        isAsync_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project2.broker.protos.Membership.internal_static_Broker_descriptor;
      }

      @java.lang.Override
      public project2.broker.protos.Membership.Broker getDefaultInstanceForType() {
        return project2.broker.protos.Membership.Broker.getDefaultInstance();
      }

      @java.lang.Override
      public project2.broker.protos.Membership.Broker build() {
        project2.broker.protos.Membership.Broker result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project2.broker.protos.Membership.Broker buildPartial() {
        project2.broker.protos.Membership.Broker result = new project2.broker.protos.Membership.Broker(this);
        result.address_ = address_;
        result.port_ = port_;
        result.partition_ = partition_;
        result.id_ = id_;
        result.isAsync_ = isAsync_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project2.broker.protos.Membership.Broker) {
          return mergeFrom((project2.broker.protos.Membership.Broker)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project2.broker.protos.Membership.Broker other) {
        if (other == project2.broker.protos.Membership.Broker.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getPartition() != 0) {
          setPartition(other.getPartition());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getIsAsync() != false) {
          setIsAsync(other.getIsAsync());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project2.broker.protos.Membership.Broker parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project2.broker.protos.Membership.Broker) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int partition_ ;
      /**
       * <code>int32 partition = 3;</code>
       * @return The partition.
       */
      @java.lang.Override
      public int getPartition() {
        return partition_;
      }
      /**
       * <code>int32 partition = 3;</code>
       * @param value The partition to set.
       * @return This builder for chaining.
       */
      public Builder setPartition(int value) {
        
        partition_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partition = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPartition() {
        
        partition_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 4;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 4;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private boolean isAsync_ ;
      /**
       * <code>bool isAsync = 5;</code>
       * @return The isAsync.
       */
      @java.lang.Override
      public boolean getIsAsync() {
        return isAsync_;
      }
      /**
       * <code>bool isAsync = 5;</code>
       * @param value The isAsync to set.
       * @return This builder for chaining.
       */
      public Builder setIsAsync(boolean value) {
        
        isAsync_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isAsync = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsAsync() {
        
        isAsync_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Broker)
    }

    // @@protoc_insertion_point(class_scope:Broker)
    private static final project2.broker.protos.Membership.Broker DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project2.broker.protos.Membership.Broker();
    }

    public static project2.broker.protos.Membership.Broker getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Broker>
        PARSER = new com.google.protobuf.AbstractParser<Broker>() {
      @java.lang.Override
      public Broker parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Broker(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Broker> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Broker> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project2.broker.protos.Membership.Broker getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MemberTableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MemberTable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    int getSize();

    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    java.util.List<project2.broker.protos.Membership.Broker> 
        getBrokersList();
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    project2.broker.protos.Membership.Broker getBrokers(int index);
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    int getBrokersCount();
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    java.util.List<? extends project2.broker.protos.Membership.BrokerOrBuilder> 
        getBrokersOrBuilderList();
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    project2.broker.protos.Membership.BrokerOrBuilder getBrokersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MemberTable}
   */
  public static final class MemberTable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MemberTable)
      MemberTableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MemberTable.newBuilder() to construct.
    private MemberTable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MemberTable() {
      brokers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MemberTable();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MemberTable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              size_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                brokers_ = new java.util.ArrayList<project2.broker.protos.Membership.Broker>();
                mutable_bitField0_ |= 0x00000001;
              }
              brokers_.add(
                  input.readMessage(project2.broker.protos.Membership.Broker.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          brokers_ = java.util.Collections.unmodifiableList(brokers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project2.broker.protos.Membership.internal_static_MemberTable_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project2.broker.protos.Membership.internal_static_MemberTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project2.broker.protos.Membership.MemberTable.class, project2.broker.protos.Membership.MemberTable.Builder.class);
    }

    public static final int SIZE_FIELD_NUMBER = 1;
    private int size_;
    /**
     * <code>int32 size = 1;</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }

    public static final int BROKERS_FIELD_NUMBER = 2;
    private java.util.List<project2.broker.protos.Membership.Broker> brokers_;
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<project2.broker.protos.Membership.Broker> getBrokersList() {
      return brokers_;
    }
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends project2.broker.protos.Membership.BrokerOrBuilder> 
        getBrokersOrBuilderList() {
      return brokers_;
    }
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    @java.lang.Override
    public int getBrokersCount() {
      return brokers_.size();
    }
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    @java.lang.Override
    public project2.broker.protos.Membership.Broker getBrokers(int index) {
      return brokers_.get(index);
    }
    /**
     * <code>repeated .Broker brokers = 2;</code>
     */
    @java.lang.Override
    public project2.broker.protos.Membership.BrokerOrBuilder getBrokersOrBuilder(
        int index) {
      return brokers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (size_ != 0) {
        output.writeInt32(1, size_);
      }
      for (int i = 0; i < brokers_.size(); i++) {
        output.writeMessage(2, brokers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, size_);
      }
      for (int i = 0; i < brokers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, brokers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project2.broker.protos.Membership.MemberTable)) {
        return super.equals(obj);
      }
      project2.broker.protos.Membership.MemberTable other = (project2.broker.protos.Membership.MemberTable) obj;

      if (getSize()
          != other.getSize()) return false;
      if (!getBrokersList()
          .equals(other.getBrokersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      if (getBrokersCount() > 0) {
        hash = (37 * hash) + BROKERS_FIELD_NUMBER;
        hash = (53 * hash) + getBrokersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project2.broker.protos.Membership.MemberTable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.broker.protos.Membership.MemberTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.MemberTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.MemberTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project2.broker.protos.Membership.MemberTable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MemberTable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MemberTable)
        project2.broker.protos.Membership.MemberTableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project2.broker.protos.Membership.internal_static_MemberTable_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project2.broker.protos.Membership.internal_static_MemberTable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project2.broker.protos.Membership.MemberTable.class, project2.broker.protos.Membership.MemberTable.Builder.class);
      }

      // Construct using project2.broker.protos.Membership.MemberTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBrokersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        size_ = 0;

        if (brokersBuilder_ == null) {
          brokers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          brokersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project2.broker.protos.Membership.internal_static_MemberTable_descriptor;
      }

      @java.lang.Override
      public project2.broker.protos.Membership.MemberTable getDefaultInstanceForType() {
        return project2.broker.protos.Membership.MemberTable.getDefaultInstance();
      }

      @java.lang.Override
      public project2.broker.protos.Membership.MemberTable build() {
        project2.broker.protos.Membership.MemberTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project2.broker.protos.Membership.MemberTable buildPartial() {
        project2.broker.protos.Membership.MemberTable result = new project2.broker.protos.Membership.MemberTable(this);
        int from_bitField0_ = bitField0_;
        result.size_ = size_;
        if (brokersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            brokers_ = java.util.Collections.unmodifiableList(brokers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.brokers_ = brokers_;
        } else {
          result.brokers_ = brokersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project2.broker.protos.Membership.MemberTable) {
          return mergeFrom((project2.broker.protos.Membership.MemberTable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project2.broker.protos.Membership.MemberTable other) {
        if (other == project2.broker.protos.Membership.MemberTable.getDefaultInstance()) return this;
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (brokersBuilder_ == null) {
          if (!other.brokers_.isEmpty()) {
            if (brokers_.isEmpty()) {
              brokers_ = other.brokers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBrokersIsMutable();
              brokers_.addAll(other.brokers_);
            }
            onChanged();
          }
        } else {
          if (!other.brokers_.isEmpty()) {
            if (brokersBuilder_.isEmpty()) {
              brokersBuilder_.dispose();
              brokersBuilder_ = null;
              brokers_ = other.brokers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              brokersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBrokersFieldBuilder() : null;
            } else {
              brokersBuilder_.addAllMessages(other.brokers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project2.broker.protos.Membership.MemberTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project2.broker.protos.Membership.MemberTable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int size_ ;
      /**
       * <code>int32 size = 1;</code>
       * @return The size.
       */
      @java.lang.Override
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 size = 1;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<project2.broker.protos.Membership.Broker> brokers_ =
        java.util.Collections.emptyList();
      private void ensureBrokersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          brokers_ = new java.util.ArrayList<project2.broker.protos.Membership.Broker>(brokers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          project2.broker.protos.Membership.Broker, project2.broker.protos.Membership.Broker.Builder, project2.broker.protos.Membership.BrokerOrBuilder> brokersBuilder_;

      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public java.util.List<project2.broker.protos.Membership.Broker> getBrokersList() {
        if (brokersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(brokers_);
        } else {
          return brokersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public int getBrokersCount() {
        if (brokersBuilder_ == null) {
          return brokers_.size();
        } else {
          return brokersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public project2.broker.protos.Membership.Broker getBrokers(int index) {
        if (brokersBuilder_ == null) {
          return brokers_.get(index);
        } else {
          return brokersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder setBrokers(
          int index, project2.broker.protos.Membership.Broker value) {
        if (brokersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokersIsMutable();
          brokers_.set(index, value);
          onChanged();
        } else {
          brokersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder setBrokers(
          int index, project2.broker.protos.Membership.Broker.Builder builderForValue) {
        if (brokersBuilder_ == null) {
          ensureBrokersIsMutable();
          brokers_.set(index, builderForValue.build());
          onChanged();
        } else {
          brokersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder addBrokers(project2.broker.protos.Membership.Broker value) {
        if (brokersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokersIsMutable();
          brokers_.add(value);
          onChanged();
        } else {
          brokersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder addBrokers(
          int index, project2.broker.protos.Membership.Broker value) {
        if (brokersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokersIsMutable();
          brokers_.add(index, value);
          onChanged();
        } else {
          brokersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder addBrokers(
          project2.broker.protos.Membership.Broker.Builder builderForValue) {
        if (brokersBuilder_ == null) {
          ensureBrokersIsMutable();
          brokers_.add(builderForValue.build());
          onChanged();
        } else {
          brokersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder addBrokers(
          int index, project2.broker.protos.Membership.Broker.Builder builderForValue) {
        if (brokersBuilder_ == null) {
          ensureBrokersIsMutable();
          brokers_.add(index, builderForValue.build());
          onChanged();
        } else {
          brokersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder addAllBrokers(
          java.lang.Iterable<? extends project2.broker.protos.Membership.Broker> values) {
        if (brokersBuilder_ == null) {
          ensureBrokersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, brokers_);
          onChanged();
        } else {
          brokersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder clearBrokers() {
        if (brokersBuilder_ == null) {
          brokers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          brokersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public Builder removeBrokers(int index) {
        if (brokersBuilder_ == null) {
          ensureBrokersIsMutable();
          brokers_.remove(index);
          onChanged();
        } else {
          brokersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public project2.broker.protos.Membership.Broker.Builder getBrokersBuilder(
          int index) {
        return getBrokersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public project2.broker.protos.Membership.BrokerOrBuilder getBrokersOrBuilder(
          int index) {
        if (brokersBuilder_ == null) {
          return brokers_.get(index);  } else {
          return brokersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public java.util.List<? extends project2.broker.protos.Membership.BrokerOrBuilder> 
           getBrokersOrBuilderList() {
        if (brokersBuilder_ != null) {
          return brokersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(brokers_);
        }
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public project2.broker.protos.Membership.Broker.Builder addBrokersBuilder() {
        return getBrokersFieldBuilder().addBuilder(
            project2.broker.protos.Membership.Broker.getDefaultInstance());
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public project2.broker.protos.Membership.Broker.Builder addBrokersBuilder(
          int index) {
        return getBrokersFieldBuilder().addBuilder(
            index, project2.broker.protos.Membership.Broker.getDefaultInstance());
      }
      /**
       * <code>repeated .Broker brokers = 2;</code>
       */
      public java.util.List<project2.broker.protos.Membership.Broker.Builder> 
           getBrokersBuilderList() {
        return getBrokersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          project2.broker.protos.Membership.Broker, project2.broker.protos.Membership.Broker.Builder, project2.broker.protos.Membership.BrokerOrBuilder> 
          getBrokersFieldBuilder() {
        if (brokersBuilder_ == null) {
          brokersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              project2.broker.protos.Membership.Broker, project2.broker.protos.Membership.Broker.Builder, project2.broker.protos.Membership.BrokerOrBuilder>(
                  brokers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          brokers_ = null;
        }
        return brokersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MemberTable)
    }

    // @@protoc_insertion_point(class_scope:MemberTable)
    private static final project2.broker.protos.Membership.MemberTable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project2.broker.protos.Membership.MemberTable();
    }

    public static project2.broker.protos.Membership.MemberTable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MemberTable>
        PARSER = new com.google.protobuf.AbstractParser<MemberTable>() {
      @java.lang.Override
      public MemberTable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MemberTable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MemberTable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MemberTable> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project2.broker.protos.Membership.MemberTable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Status)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes list = 1;</code>
     * @return A list containing the list.
     */
    java.util.List<com.google.protobuf.ByteString> getListList();
    /**
     * <code>repeated bytes list = 1;</code>
     * @return The count of list.
     */
    int getListCount();
    /**
     * <code>repeated bytes list = 1;</code>
     * @param index The index of the element to return.
     * @return The list at the given index.
     */
    com.google.protobuf.ByteString getList(int index);
  }
  /**
   * Protobuf type {@code Status}
   */
  public static final class Status extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Status)
      StatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Status.newBuilder() to construct.
    private Status(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Status() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Status();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Status(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                list_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readBytes());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return project2.broker.protos.Membership.internal_static_Status_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return project2.broker.protos.Membership.internal_static_Status_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              project2.broker.protos.Membership.Status.class, project2.broker.protos.Membership.Status.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> list_;
    /**
     * <code>repeated bytes list = 1;</code>
     * @return A list containing the list.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getListList() {
      return list_;
    }
    /**
     * <code>repeated bytes list = 1;</code>
     * @return The count of list.
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated bytes list = 1;</code>
     * @param index The index of the element to return.
     * @return The list at the given index.
     */
    public com.google.protobuf.ByteString getList(int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeBytes(1, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < list_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(list_.get(i));
        }
        size += dataSize;
        size += 1 * getListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof project2.broker.protos.Membership.Status)) {
        return super.equals(obj);
      }
      project2.broker.protos.Membership.Status other = (project2.broker.protos.Membership.Status) obj;

      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static project2.broker.protos.Membership.Status parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Status parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Status parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Status parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.Status parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static project2.broker.protos.Membership.Status parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(project2.broker.protos.Membership.Status prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Status}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Status)
        project2.broker.protos.Membership.StatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return project2.broker.protos.Membership.internal_static_Status_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return project2.broker.protos.Membership.internal_static_Status_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                project2.broker.protos.Membership.Status.class, project2.broker.protos.Membership.Status.Builder.class);
      }

      // Construct using project2.broker.protos.Membership.Status.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return project2.broker.protos.Membership.internal_static_Status_descriptor;
      }

      @java.lang.Override
      public project2.broker.protos.Membership.Status getDefaultInstanceForType() {
        return project2.broker.protos.Membership.Status.getDefaultInstance();
      }

      @java.lang.Override
      public project2.broker.protos.Membership.Status build() {
        project2.broker.protos.Membership.Status result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public project2.broker.protos.Membership.Status buildPartial() {
        project2.broker.protos.Membership.Status result = new project2.broker.protos.Membership.Status(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.list_ = list_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof project2.broker.protos.Membership.Status) {
          return mergeFrom((project2.broker.protos.Membership.Status)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(project2.broker.protos.Membership.Status other) {
        if (other == project2.broker.protos.Membership.Status.getDefaultInstance()) return this;
        if (!other.list_.isEmpty()) {
          if (list_.isEmpty()) {
            list_ = other.list_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureListIsMutable();
            list_.addAll(other.list_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        project2.broker.protos.Membership.Status parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (project2.broker.protos.Membership.Status) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> list_ = java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          list_ = new java.util.ArrayList<com.google.protobuf.ByteString>(list_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @return A list containing the list.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getListList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(list_) : list_;
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @return The count of list.
       */
      public int getListCount() {
        return list_.size();
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @param index The index of the element to return.
       * @return The list at the given index.
       */
      public com.google.protobuf.ByteString getList(int index) {
        return list_.get(index);
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @param index The index to set the value at.
       * @param value The list to set.
       * @return This builder for chaining.
       */
      public Builder setList(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @param value The list to add.
       * @return This builder for chaining.
       */
      public Builder addList(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
        list_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @param values The list to add.
       * @return This builder for chaining.
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, list_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes list = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearList() {
        list_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Status)
    }

    // @@protoc_insertion_point(class_scope:Status)
    private static final project2.broker.protos.Membership.Status DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new project2.broker.protos.Membership.Status();
    }

    public static project2.broker.protos.Membership.Status getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Status>
        PARSER = new com.google.protobuf.AbstractParser<Status>() {
      @java.lang.Override
      public Status parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Status(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Status> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Status> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public project2.broker.protos.Membership.Status getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Broker_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Broker_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MemberTable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MemberTable_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027protos/memberShip.proto\"W\n\006Broker\022\017\n\007a" +
      "ddress\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\021\n\tpartition\030" +
      "\003 \001(\005\022\n\n\002id\030\004 \001(\005\022\017\n\007isAsync\030\005 \001(\010\"5\n\013Me" +
      "mberTable\022\014\n\004size\030\001 \001(\005\022\030\n\007brokers\030\002 \003(\013" +
      "2\007.Broker\"\026\n\006Status\022\014\n\004list\030\001 \003(\014B$\n\026pro" +
      "ject2.broker.protosB\nMembershipb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Broker_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Broker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Broker_descriptor,
        new java.lang.String[] { "Address", "Port", "Partition", "Id", "IsAsync", });
    internal_static_MemberTable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MemberTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MemberTable_descriptor,
        new java.lang.String[] { "Size", "Brokers", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
